config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get    'signup', to: 'users#new'
  get    'login' , to: 'sessions#new'
  post   'login' , to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  #get    'followed', to: 'users#followed'
  #get    'follower', to: 'users#follower'
  
  resources :users do
    member do 
      get 'followings','followers'
    end
  end
  resources :users do
    member do 
      get 'iine'
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts
  resources :relationships, only: [:create, :destroy]
  resources :like_relationships, only: [:create, :destroy]
  resources :micropostrelationships, only: [:create, :destroy]
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  has_many :iine_relationships, class_name: "Micropostrelationship",
                                foreign_key:  "micropost_id",
                                dependent:  :destroy
  has_many :iinesita_users, through: :iine_relationships, source: :user
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only: [:create]

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to root_url
    else
      @feed_items = current_user.feed_items.includes(:user).order(created_at: :desc) # この行を追加
      render 'static_pages/home'
    end
  end
  
  def destroy
    @micropost = current_user.microposts.find_by(id: params[:id])
    return redirect_to root_url if @micropost.nil?
    @micropost.destroy
    flash[:success] = "Micropost deleted"
    redirect_to request.referrer || root_url
  end
  
  private
  def micropost_params
    params.require(:micropost).permit(:content)
  end
end

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content"><%= micropost.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
    
    <% if current_user ==micropost.user %>
        <%= link_to "delete", micropost, method: :delete,
                                        data: { confirm: "You sure?" } %>
    <% end %>
    <% if current_user !=micropost.user %>
    <% if logged_in? %>
    <% end %>
    <% end %>
    <% if current_user.iine?(micropost) %>
      <%= link_to 'いいねを取り消す', micropostrelationship_path(micropost), method: :delete %>
    <% else %>
      <%= link_to "いいね", micropostrelationships_path(micropost_id: micropost.id), method: :post %>
    <% end %>
  </span>
</li>