config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get    'signup', to: 'users#new'
  get    'login' , to: 'sessions#new'
  post   'login' , to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  #get    'followed', to: 'users#followed'
  #get    'follower', to: 'users#follower'
  
  resources :users do
    member do 
      get 'followings','followers'
    end
  end
  resources :users do
    member do 
      get 'iine'
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts
  resources :relationships, only: [:create, :destroy]
  resources :like_relationships, only: [:create, :destroy]
  resources :micropostrelationships, only: [:create, :destroy]
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Microposts", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help",   '#' %></li>
        <% if logged_in? %>
        <li><%= link_to "Users", '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
        <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_profile.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
     <%= render 'shared/error_messages', object: f.object %> <!-- ここを追加 -->

    <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

    <%= f.label :Email %>
      <%= f.text_field :email, class: 'form-control' %>
  
    <%= f.label :location %>
      <%= f.text_field :location, class: 'form-control' %>
  
     <%= f.label :About %>
      <%= f.text_area :about, class: 'form-control' %>
    
    <%= f.label :password %>
      <%= f.password_field :password,class: 'form-control' %>

    <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation,class: 'form-control' %>

    <%= f.submit class: "btn btn-sm btn-primary" %>

    <% end %>

  </div>
</div>

app/views/layouts/_profilepartial.html.erb
      <h1>
        <%= gravatar_for @user %><br />
        <%= @user.name %> <br />
      </h1>
     <div class="textcolumn"> 
         <%= link_to "ツイート", user_path(@user) %><br /><br />
         <%= link_to "フォロワー", followers_user_path(@user) %><br /><br />
         <%= link_to "フォロー", followings_user_path(@user) %><br /><br />
         <%= link_to "いいね", iine_user_path(@user) %><br /> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Micropost</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %> <!-- ここから -->
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %> 
<%= yield %>
  </div>
</body>
</html>